analyzer:
  errors:
    prefer_const_declarations: error
    prefer_relative_imports: error
    avoid_empty_else: warning
    prefer_const_constructors: error
    prefer_single_quotes: warning
    prefer_final_fields: error
    prefer_final_locals: error

linter:
  rules:
    - prefer_const_declarations
    - prefer_relative_imports
    - avoid_empty_else
    - prefer_const_constructors
    - prefer_single_quotes
    - prefer_final_fields
    - prefer_final_locals