# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Runner
  pod 'NearbyMessages'
end